version: "3.3"
services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: symfony-in-docker-mysql
    environment:
      MYSQL_DATABASE: symfony-in-docker
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "33060:3306"

  php-fpm:
    image: webdevops/php-dev:7.3
    hostname: php-fpm
    container_name: symfony-in-docker-php-fpm
    volumes:
      - "./:/app"
    working_dir: "/app"
    depends_on:
      - mysql

  nginx:
    image: webdevops/nginx
    hostname: nginx
    container_name: symfony-in-docker-nginx
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php-fpm:9000
    ports:
      - "80:80"
    volumes:
      - "./:/app"
    depends_on:
      - php-fpm

  composer:
    restart: "no"
    container_name: symfony-in-docker-composer
    image: composer:1.8.5
    command: install --ignore-platform-reqs
    working_dir: /app
    volumes:
      - "./:/app"
